<a href="https://colab.research.google.com/github/ryannugroho/Preprocessing_Data/blob/main/Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [39]:
dataset = pd.read_csv('Tomato.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [40]:
print(str(x)+"\n")
print(y)

[['2013-06-16' 'Kg' 26 32 29.0]
 ['2013-06-17' 'Kg' 20 25 22.5]
 ['2013-06-18' 'Kg' 22 26 24.0]
 ...
 ['2021-05-11' 'Kg' 10 15 12.5]
 ['2021-05-12' 'Kg' 30 35 32.5]
 ['2021-05-13' 'Kg' 35 40 37.5]]

['Tomato' 'Tomato' 'Tomato' ... 'Tomato' 'Tomato' 'Tomato']


In [43]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer (missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 2:5])
x[:, 2:5] = imputer.transform(x[:, 2:5])

In [42]:
print(x)

[['2013-06-16' 'Kg' 26 32 29.0]
 ['2013-06-17' 'Kg' 20 25 22.5]
 ['2013-06-18' 'Kg' 22 26 24.0]
 ...
 ['2021-05-11' 'Kg' 10 15 12.5]
 ['2021-05-12' 'Kg' 30 35 32.5]
 ['2021-05-13' 'Kg' 35 40 37.5]]


In [44]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer (transformers=[ ('encoder' , OneHotEncoder(sparse_output=False), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(x))

In [45]:
print(X)

[[1.0 0.0 0.0 ... 26.0 32.0 29.0]
 [0.0 1.0 0.0 ... 20.0 25.0 22.5]
 [0.0 0.0 1.0 ... 22.0 26.0 24.0]
 ...
 [0.0 0.0 0.0 ... 10.0 15.0 12.5]
 [0.0 0.0 0.0 ... 30.0 35.0 32.5]
 [0.0 0.0 0.0 ... 35.0 40.0 37.5]]


In [46]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [47]:
print(y)

[0 0 0 ... 0 0 0]


In [48]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [49]:
print(X_train)

[[0.0 0.0 0.0 ... 20.0 25.0 22.5]
 [0.0 0.0 0.0 ... 24.0 30.0 27.0]
 [0.0 0.0 0.0 ... 55.0 65.0 60.0]
 ...
 [0.0 0.0 0.0 ... 65.0 75.0 70.0]
 [0.0 0.0 0.0 ... 40.0 45.0 42.5]
 [0.0 0.0 0.0 ... 45.0 55.0 50.0]]


In [50]:
print(X_test)

[[0.0 0.0 0.0 ... 50.0 55.0 52.5]
 [0.0 0.0 0.0 ... 80.0 85.0 82.5]
 [0.0 0.0 0.0 ... 35.0 40.0 37.5]
 ...
 [0.0 0.0 0.0 ... 52.0 58.0 55.0]
 [0.0 0.0 0.0 ... 55.0 65.0 60.0]
 [0.0 0.0 0.0 ... 30.0 35.0 32.5]]


In [51]:
print(y_train)

[0 0 0 ... 0 0 0]


In [52]:
print(y_test)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 

In [53]:
from sklearn. preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,:5] = sc.fit_transform(X_train[:,:5])
X_test[:,:5] = sc.transform(X_test[:,:5])

In [54]:
print(X_train)

[[-0.021363815131845317 -0.021363815131845227 -0.021363815131845484 ...
  20.0 25.0 22.5]
 [-0.021363815131845317 -0.021363815131845227 -0.021363815131845484 ...
  24.0 30.0 27.0]
 [-0.021363815131845317 -0.021363815131845227 -0.021363815131845484 ...
  55.0 65.0 60.0]
 ...
 [-0.021363815131845317 -0.021363815131845227 -0.021363815131845484 ...
  65.0 75.0 70.0]
 [-0.021363815131845317 -0.021363815131845227 -0.021363815131845484 ...
  40.0 45.0 42.5]
 [-0.021363815131845317 -0.021363815131845227 -0.021363815131845484 ...
  45.0 55.0 50.0]]


In [55]:
print(X_test)

[[-0.021363815131845317 -0.021363815131845227 -0.021363815131845484 ...
  50.0 55.0 52.5]
 [-0.021363815131845317 -0.021363815131845227 -0.021363815131845484 ...
  80.0 85.0 82.5]
 [-0.021363815131845317 -0.021363815131845227 -0.021363815131845484 ...
  35.0 40.0 37.5]
 ...
 [-0.021363815131845317 -0.021363815131845227 -0.021363815131845484 ...
  52.0 58.0 55.0]
 [-0.021363815131845317 -0.021363815131845227 -0.021363815131845484 ...
  55.0 65.0 60.0]
 [-0.021363815131845317 -0.021363815131845227 -0.021363815131845484 ...
  30.0 35.0 32.5]]
