<a href="https://colab.research.google.com/github/ryannugroho/Preprocessing_Data/blob/main/Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset = pd.read_csv('Tomato.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(str(x)+"\n")
print(y)

[['2013-06-16' 'Kg' 26 32 29.0]
 ['2013-06-17' 'Kg' 20 25 22.5]
 ['2013-06-18' 'Kg' 22 26 24.0]
 ...
 ['2021-05-11' 'Kg' 10 15 12.5]
 ['2021-05-12' 'Kg' 30 35 32.5]
 ['2021-05-13' 'Kg' 35 40 37.5]]

['Tomato' 'Tomato' 'Tomato' ... 'Tomato' 'Tomato' 'Tomato']


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer (missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 2:3])
x[:, 2:3] = imputer.transform(x[:, 2:3])

In [ ]:
print(x)

[['2013-06-16' 'Kg' 26.0 32 29.0]
 ['2013-06-17' 'Kg' 20.0 25 22.5]
 ['2013-06-18' 'Kg' 22.0 26 24.0]
 ...
 ['2021-05-11' 'Kg' 10.0 15 12.5]
 ['2021-05-12' 'Kg' 30.0 35 32.5]
 ['2021-05-13' 'Kg' 35.0 40 37.5]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer (transformers=[ ('encoder' , OneHotEncoder(sparse_output=False), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(x))

In [ ]:
print(X)

[[1.0 0.0 0.0 ... 26.0 32 29.0]
 [0.0 1.0 0.0 ... 20.0 25 22.5]
 [0.0 0.0 1.0 ... 22.0 26 24.0]
 ...
 [0.0 0.0 0.0 ... 10.0 15 12.5]
 [0.0 0.0 0.0 ... 30.0 35 32.5]
 [0.0 0.0 0.0 ... 35.0 40 37.5]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[0 0 0 ... 0 0 0]


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [ ]:
print(X_train)

[[0.0 0.0 0.0 ... 20.0 25 22.5]
 [0.0 0.0 0.0 ... 24.0 30 27.0]
 [0.0 0.0 0.0 ... 55.0 65 60.0]
 ...
 [0.0 0.0 0.0 ... 65.0 75 70.0]
 [0.0 0.0 0.0 ... 40.0 45 42.5]
 [0.0 0.0 0.0 ... 45.0 55 50.0]]


In [ ]:
print(X_test)

[[0.0 0.0 0.0 ... 50.0 55 52.5]
 [0.0 0.0 0.0 ... 80.0 85 82.5]
 [0.0 0.0 0.0 ... 35.0 40 37.5]
 ...
 [0.0 0.0 0.0 ... 52.0 58 55.0]
 [0.0 0.0 0.0 ... 55.0 65 60.0]
 [0.0 0.0 0.0 ... 30.0 35 32.5]]


In [ ]:
print(y_train)

[0 0 0 ... 0 0 0]


In [ ]:
print(y_test)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 

In [ ]:
from sklearn. preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 1:3] = sc.fit_transform(X_train[:, 1:3])
X_test[:, 1:3] = sc.transform(X_test[:, 1:3])

In [ ]:
print(X_train)

[[0.0 -0.021363815131844557 -0.021363815131845428 ... 20.0 25 22.5]
 [0.0 -0.021363815131844557 -0.021363815131845428 ... 24.0 30 27.0]
 [0.0 -0.021363815131844557 -0.021363815131845428 ... 55.0 65 60.0]
 ...
 [0.0 -0.021363815131844557 -0.021363815131845428 ... 65.0 75 70.0]
 [0.0 -0.021363815131844557 -0.021363815131845428 ... 40.0 45 42.5]
 [0.0 -0.021363815131844557 -0.021363815131845428 ... 45.0 55 50.0]]


In [ ]:
print(X_test)

[[0.0 -0.021363815131845227 -0.021363815131845654 ... 50.0 55 52.5]
 [0.0 -0.021363815131845227 -0.021363815131845654 ... 80.0 85 82.5]
 [0.0 -0.021363815131845227 -0.021363815131845654 ... 35.0 40 37.5]
 ...
 [0.0 -0.021363815131845227 -0.021363815131845654 ... 52.0 58 55.0]
 [0.0 -0.021363815131845227 -0.021363815131845654 ... 55.0 65 60.0]
 [0.0 -0.021363815131845227 -0.021363815131845654 ... 30.0 35 32.5]]
